### ISSUE TITLE
What about join forces?

### ISSUE THREAD

**Issue by sonomirco** [karakasa/Pancake.ManagedGeometry#2]
Hey man,
what about join GShark and collaborating with us?
https://github.com/GSharker/G-Shark

**Comment by karakasa** [comment]
I reviewed your project and I think your project's goal differs from mine.
I may contribute, though. There's a lot of room for performance improvement in your project.

**Comment by sonomirco** [comment]
Yeah cool.
We are not looking for performance at this stage, but happy to have feedback about it :)
